Upgrade to allow PHP 8
MyOnlineStore/coding-standard pull request #10
Opened 2020-10-23 10:41 UTC by frankverhoeven

Allow the package to be used with PHP 8.
Upgrades Doctrine Coding-Standard from `7.x` to `8.x`, which includes [PSR-12](https://www.php-fig.org/psr/psr-12/).

Notable breaking changes (from PSR-12):
- Spaces are now required before and after `.` operator.
- Multi-line if-statements must start on a new line, eg:
```php
if ($foo->isBar() &&
    $bar->isFoo()
) {}

// Becomes

if (
    $foo->isBar() &&
    $bar->isFoo()
) {}
```

2020-10-23 11:45 UTC, jordyk approved these changes

2020-10-27 09:57 UTC, digibeuk requested changes
don't really like the removal of zero concatenation spacing, this would mean a lot of changes in the codebase(s) let's leave that like it is for the rest : :+1:

2020-10-27 10:05 UTC, frankverhoeven commented
> don't really like the removal of zero concatenation spacing, this would mean a lot of changes in the codebase(s) let's leave that like it is for the rest : 👍

It would certainly mean a lot of changes, but these can be done in a single PR by code sniffer. It is possible to automatically fix just a single rule, ignoring all other rules. In my opinion, spaces around the concatenation improves readability. Moreover, it also makes our codebase compatible with the PSR standard.

2020-10-28 10:23 UTC, digibeuk commented
> > don't really like the removal of zero concatenation spacing, this would mean a lot of changes in the codebase(s) let's leave that like it is for the rest : +1
> 
> It would certainly mean a lot of changes, but these can be done in a single PR by code sniffer. It is possible to automatically fix just a single rule, ignoring all other rules. In my opinion, spaces around the concatenation improves readability. Moreover, it also makes our codebase compatible with the PSR standard.

o.k. on second thought I will go for your suggestion to drop it, it is more in line with the coding convention from doctrine, the less deviations we have the better. We will add per-project changes if needed as I don't want to reformat entire codebases (again)

2020-10-28 10:23 UTC, digibeuk approved these changes

2020-10-28 10:28 UTC, fred-jan approved these changes
LGTM (although my eyes are still burning from looking at that multi line if-statement)

2020-10-28 14:12 UTC, merged